# See https://github.com/airbnb/javascript/tree/eslint-config-airbnb-v16.1.0#strings--quotes
singleQuote: true

# See https://github.com/airbnb/javascript/tree/eslint-config-airbnb-v16.1.0#whitespace--max-len
printWidth: 100
